print("Prueba de Print")
print(0o105)
print(0x045)
print("Me gusta \"Monty Python\"")
print('Me encanta "estudiar"')
print("I\'m Monty Python.")
print('I"'"m Monty Python."'')
print(True > False)
print(True < False)
print("\"I'm\"\n\"\"learning\"\"\n\"\"\"Python\"\"\"")
print("En aplicaciones de resta, el operador de resta espera dos argumentos: el izquierdo un minuendo en términos aritméticos y el derecho (un sustraendo).")
print (2 + 3 * 5)